### ISSUE TITLE
Question: Finders

### ISSUE THREAD

**Issue by cabgfx** [fnando/coupons#7]
First off, thank you for such an awesome piece of work!
This gem has helped us tremendously in the past week :+1: :heart: 

I was a bit confused about the finders that come with the engine by default.
Specifically, the larger/smaller discount finders. I'm not entirely sure of how/when these would be applicable.

Did you have a specific use case in mind for these two finders?

**Comment by fnando** [comment]
Imagine you create one discount of 10% off that never expires. Then imagine you create the same code which gives $50 off, no matter what the value is. That's one way you can use larger/smaller finders.

I don't want to make assumptions about how the coupon system can be used, so that's why you can define a finder that works in any way you want. Makes sense?
